"use strict";

// category, Italian, English, German, Spanish, French, Russian, Chinese, Japanese
const phrasePack = [
  ["help","Puoi ripetere, per favore?","Could you repeat that, please?","Könnten Sie das bitte wiederholen?","¿Puedes repetirlo, por favor?","Vous pouvez répéter, s’il vous plaît ?","Повторите, пожалуйста.","请再说一遍。","もう一度お願いします。"],
  ["help","Puoi parlare più lentamente?","Could you speak more slowly?","Könnten Sie bitte langsamer sprechen?","¿Puedes hablar más despacio?","Vous pouvez parler plus lentement ?","Говорите, пожалуйста, медленнее.","请说慢一点。","もう少しゆっくり話してください。"],
  ["help","Non ho capito.","I didn’t understand.","Ich habe das nicht verstanden.","No he entendido.","Je n’ai pas compris.","Я не понял.","我没听懂。","分かりませんでした。"],
  ["help","Che cosa significa questa parola?","What does this word mean?","Was bedeutet dieses Wort?","¿Qué significa esta palabra?","Que veut dire ce mot ?","Что означает это слово?","这个词是什么意思？","この言葉はどういう意味ですか。"],
  ["help","Puoi scriverlo?","Could you write it down?","Könnten Sie das aufschreiben?","¿Puedes escribirlo?","Vous pouvez l’écrire ?","Напишите это, пожалуйста.","可以写下来吗？","書いてもらえますか。"],
  ["help","Come si scrive?","How do you spell it?","Wie schreibt man das?","¿Cómo se escribe?","Comment ça s’écrit ?","Как это пишется?","这个怎么写？","どう書きますか。"],
  ["help","Ho capito bene?","Did I understand correctly?","Habe ich das richtig verstanden?","¿Lo he entendido bien?","J’ai bien compris ?","Я правильно понял?","我理解得对吗？","この理解で合っていますか。"],
  ["help","Vuoi dire questo?","Do you mean this?","Meinen Sie das?","¿Quieres decir esto?","Vous voulez dire ceci ?","Вы имеете в виду это?","你是这个意思吗？","こういう意味ですか。"],
  ["help","Puoi mostrarmelo?","Could you show me?","Könnten Sie es mir zeigen?","¿Puedes enseñármelo?","Vous pouvez me montrer ?","Покажите мне, пожалуйста.","可以给我看一下吗？","見せてもらえますか。"],
  ["help","Puoi fare un esempio?","Could you give me an example?","Könnten Sie ein Beispiel geben?","¿Puedes darme un ejemplo?","Vous pouvez donner un exemple ?","Можете привести пример?","可以举个例子吗？","例を挙げてもらえますか。"],
  ["help","Un momento, per favore.","One moment, please.","Einen Moment, bitte.","Un momento, por favor.","Un instant, s’il vous plaît.","Одну минуту, пожалуйста.","请稍等。","少々お待ちください。"],
  ["help","Fammi pensare.","Let me think.","Lassen Sie mich kurz überlegen.","Déjame pensar.","Laissez-moi réfléchir.","Дайте мне подумать.","让我想一想。","少し考えさせてください。"],
  ["help","Sto ancora imparando.","I’m still learning.","Ich lerne noch.","Todavía estoy aprendiendo.","J’apprends encore.","Я ещё учусь.","我还在学习。","まだ勉強中です。"],
  ["help","Parlo solo un po’.","I only speak a little.","Ich spreche nur ein wenig.","Solo hablo un poco.","Je parle seulement un peu.","Я говорю совсем немного.","我只会说一点。","少しだけ話せます。"],
  ["help","Possiamo usare parole più semplici?","Could we use simpler words?","Können wir einfachere Wörter benutzen?","¿Podemos usar palabras más sencillas?","On peut utiliser des mots plus simples ?","Можно говорить проще?","可以说得简单一点吗？","もっと簡単な言葉で話せますか。"],
  ["help","Puoi indicarmelo?","Could you point to it?","Könnten Sie darauf zeigen?","¿Puedes señalarlo?","Vous pouvez me l’indiquer ?","Покажите пальцем, пожалуйста.","可以指给我看吗？","指で示してもらえますか。"],
  ["help","Quale dei due?","Which one?","Welches davon?","¿Cuál de los dos?","Lequel des deux ?","Который из них?","是哪一个？","どちらですか。"],
  ["help","È corretto così?","Is this correct?","Ist das so richtig?","¿Así está bien?","C’est correct comme ça ?","Так правильно?","这样对吗？","これで合っていますか。"],
  ["help","Puoi aiutarmi?","Can you help me?","Können Sie mir helfen?","¿Puedes ayudarme?","Vous pouvez m’aider ?","Вы можете мне помочь?","可以帮我吗？","手伝ってもらえますか。"],
  ["help","Grazie per la pazienza.","Thank you for your patience.","Danke für Ihre Geduld.","Gracias por tu paciencia.","Merci pour votre patience.","Спасибо за терпение.","谢谢你的耐心。","丁寧にありがとうございます。"],

  ["home","Sto cercando un appartamento.","I’m looking for an apartment.","Ich suche eine Wohnung.","Estoy buscando un piso.","Je cherche un appartement.","Я ищу квартиру.","我在找房子。","部屋を探しています。"],
  ["home","Quanto costa l’affitto al mese?","How much is the rent per month?","Wie hoch ist die Miete pro Monat?","¿Cuánto cuesta el alquiler al mes?","Quel est le loyer mensuel ?","Сколько стоит аренда в месяц?","每月房租是多少？","家賃は月にいくらですか。"],
  ["home","Le spese sono incluse?","Are utilities included?","Sind die Nebenkosten inbegriffen?","¿Los gastos están incluidos?","Les charges sont comprises ?","Коммунальные услуги включены?","水电费包括在内吗？","光熱費は含まれていますか。"],
  ["home","Quanto è il deposito?","How much is the deposit?","Wie hoch ist die Kaution?","¿De cuánto es la fianza?","Quel est le montant de la caution ?","Какой размер залога?","押金是多少？","敷金はいくらですか。"],
  ["home","Posso leggere il contratto?","Can I read the contract?","Kann ich den Vertrag lesen?","¿Puedo leer el contrato?","Je peux lire le contrat ?","Можно прочитать договор?","我可以看看合同吗？","契約書を確認してもいいですか。"],
  ["home","La stanza è arredata?","Is the room furnished?","Ist das Zimmer möbliert?","¿La habitación está amueblada?","La chambre est meublée ?","Комната меблирована?","房间带家具吗？","家具は付いていますか。"],
  ["home","C’è una connessione internet?","Is there an internet connection?","Gibt es einen Internetanschluss?","¿Hay conexión a internet?","Il y a une connexion internet ?","Есть интернет?","这里有网络吗？","インターネットは使えますか。"],
  ["home","Il riscaldamento non funziona.","The heating isn’t working.","Die Heizung funktioniert nicht.","La calefacción no funciona.","Le chauffage ne fonctionne pas.","Отопление не работает.","暖气坏了。","暖房が動きません。"],
  ["home","C’è una perdita d’acqua.","There is a water leak.","Es gibt ein Wasserleck.","Hay una fuga de agua.","Il y a une fuite d’eau.","Здесь протечка воды.","这里漏水了。","水漏れしています。"],
  ["home","È saltata la corrente.","The power is out.","Der Strom ist ausgefallen.","Se ha ido la luz.","Il y a une coupure de courant.","Отключили электричество.","停电了。","停電しています。"],
  ["home","Ho perso le chiavi.","I lost my keys.","Ich habe meine Schlüssel verloren.","He perdido las llaves.","J’ai perdu mes clés.","Я потерял ключи.","我把钥匙弄丢了。","鍵をなくしました。"],
  ["home","Dove si butta la spazzatura?","Where do I take the rubbish?","Wo kann ich den Müll wegwerfen?","¿Dónde se tira la basura?","Où est-ce qu’on jette les poubelles ?","Куда выбрасывать мусор?","垃圾扔在哪里？","ごみはどこに出しますか。"],
  ["home","Quali sono gli orari di silenzio?","What are the quiet hours?","Wann gelten die Ruhezeiten?","¿Cuál es el horario de silencio?","Quelles sont les heures de silence ?","Когда нужно соблюдать тишину?","安静时间是什么时候？","静かにする時間は何時ですか。"],
  ["home","Vorrei parlare con il vicino.","I’d like to speak to the neighbour.","Ich möchte mit dem Nachbarn sprechen.","Quisiera hablar con el vecino.","Je voudrais parler au voisin.","Я хотел бы поговорить с соседом.","我想和邻居谈谈。","隣の人と話したいです。"],
  ["home","Quando può venire il tecnico?","When can the technician come?","Wann kann der Techniker kommen?","¿Cuándo puede venir el técnico?","Quand le technicien peut-il venir ?","Когда может прийти мастер?","维修人员什么时候能来？","修理の方はいつ来られますか。"],
  ["home","Quando posso trasferirmi?","When can I move in?","Wann kann ich einziehen?","¿Cuándo puedo mudarme?","Quand puis-je emménager ?","Когда можно заселиться?","我什么时候可以入住？","いつ入居できますか。"],

  ["work","A che ora inizio?","What time do I start?","Um wie viel Uhr fange ich an?","¿A qué hora empiezo?","À quelle heure est-ce que je commence ?","Во сколько я начинаю?","我几点开始上班？","何時から始めますか。"],
  ["work","Qual è il mio orario di oggi?","What is my schedule today?","Wie ist mein heutiger Arbeitsplan?","¿Cuál es mi horario de hoy?","Quel est mon planning aujourd’hui ?","Какой у меня сегодня график?","我今天的工作安排是什么？","今日の予定は何ですか。"],
  ["work","Puoi ripetere il compito?","Could you repeat the task?","Könnten Sie die Aufgabe wiederholen?","¿Puedes repetir la tarea?","Vous pouvez répéter la tâche ?","Повторите задание, пожалуйста.","可以再说一遍任务吗？","作業内容をもう一度お願いします。"],
  ["work","Qual è la scadenza?","What is the deadline?","Wann ist die Frist?","¿Cuál es la fecha límite?","Quelle est la date limite ?","Какой срок?","截止日期是什么时候？","締め切りはいつですか。"],
  ["work","Qual è la priorità?","What is the priority?","Was hat Priorität?","¿Cuál es la prioridad?","Quelle est la priorité ?","Что важнее всего?","哪项任务最优先？","何を優先すればいいですか。"],
  ["work","Come devo farlo?","How should I do this?","Wie soll ich das machen?","¿Cómo debo hacerlo?","Comment dois-je faire ?","Как мне это сделать?","这个应该怎么做？","これはどうすればいいですか。"],
  ["work","Puoi mostrarmi la procedura?","Could you show me the process?","Könnten Sie mir den Ablauf zeigen?","¿Puedes enseñarme el proceso?","Vous pouvez me montrer la procédure ?","Покажите мне порядок действий.","可以给我演示一下流程吗？","手順を見せてもらえますか。"],
  ["work","Ho finito questo compito.","I’ve finished this task.","Ich habe diese Aufgabe erledigt.","He terminado esta tarea.","J’ai terminé cette tâche.","Я закончил это задание.","这项任务我做完了。","この作業は終わりました。"],
  ["work","Mi serve più tempo.","I need more time.","Ich brauche mehr Zeit.","Necesito más tiempo.","J’ai besoin de plus de temps.","Мне нужно больше времени.","我需要更多时间。","もう少し時間が必要です。"],
  ["work","C’è un problema.","There is a problem.","Es gibt ein Problem.","Hay un problema.","Il y a un problème.","Возникла проблема.","有一个问题。","問題があります。"],
  ["work","Vorrei chiarire un dettaglio.","I’d like to clarify one detail.","Ich möchte ein Detail klären.","Quisiera aclarar un detalle.","Je voudrais clarifier un point.","Я хотел бы уточнить одну деталь.","我想确认一个细节。","一点確認したいことがあります。"],
  ["work","Ti mando tutto per email.","I’ll send everything by email.","Ich schicke alles per E-Mail.","Te lo envío todo por correo.","Je vous envoie tout par e-mail.","Я отправлю всё по электронной почте.","我会通过邮件发送全部内容。","すべてメールで送ります。"],
  ["work","Quando posso fare una pausa?","When can I take a break?","Wann kann ich Pause machen?","¿Cuándo puedo tomar un descanso?","Quand puis-je faire une pause ?","Когда можно сделать перерыв?","我什么时候可以休息？","休憩はいつ取れますか。"],
  ["work","Puoi darmi un feedback?","Could you give me some feedback?","Könnten Sie mir Feedback geben?","¿Puedes darme tu opinión?","Vous pouvez me faire un retour ?","Можете дать мне обратную связь?","可以给我一些反馈吗？","フィードバックをいただけますか。"],
  ["work","Sono d’accordo con questa soluzione.","I agree with this solution.","Ich stimme dieser Lösung zu.","Estoy de acuerdo con esta solución.","Je suis d’accord avec cette solution.","Я согласен с этим решением.","我同意这个解决方案。","この解決策に賛成です。"],
  ["work","Non ho capito questo requisito.","I don’t understand this requirement.","Ich verstehe diese Anforderung nicht.","No entiendo este requisito.","Je ne comprends pas cette exigence.","Я не понимаю это требование.","我不明白这个要求。","この要件が分かりません。"],

  ["health","Ho bisogno di un medico.","I need a doctor.","Ich brauche einen Arzt.","Necesito un médico.","J’ai besoin d’un médecin.","Мне нужен врач.","我需要看医生。","医師に診てもらいたいです。"],
  ["health","Non mi sento bene.","I don’t feel well.","Ich fühle mich nicht gut.","No me siento bien.","Je ne me sens pas bien.","Я плохо себя чувствую.","我不舒服。","具合がよくありません。"],
  ["health","Ho la febbre.","I have a fever.","Ich habe Fieber.","Tengo fiebre.","J’ai de la fièvre.","У меня температура.","我发烧了。","熱があります。"],
  ["health","Mi fa male qui.","It hurts here.","Hier tut es weh.","Me duele aquí.","J’ai mal ici.","У меня болит здесь.","我这里疼。","ここが痛いです。"],
  ["health","È iniziato ieri.","It started yesterday.","Es hat gestern angefangen.","Empezó ayer.","Ça a commencé hier.","Это началось вчера.","昨天开始的。","昨日からです。"],
  ["health","Sono allergico a questo.","I’m allergic to this.","Ich bin dagegen allergisch.","Soy alérgico a esto.","Je suis allergique à cela.","У меня на это аллергия.","我对这个过敏。","これにアレルギーがあります。"],
  ["health","Prendo questo farmaco.","I take this medicine.","Ich nehme dieses Medikament.","Tomo este medicamento.","Je prends ce médicament.","Я принимаю это лекарство.","我在服用这种药。","この薬を飲んでいます。"],
  ["health","Quante volte al giorno?","How many times a day?","Wie oft am Tag?","¿Cuántas veces al día?","Combien de fois par jour ?","Сколько раз в день?","一天几次？","一日に何回ですか。"],
  ["health","Dov’è la farmacia più vicina?","Where is the nearest pharmacy?","Wo ist die nächste Apotheke?","¿Dónde está la farmacia más cercana?","Où est la pharmacie la plus proche ?","Где ближайшая аптека?","最近的药店在哪里？","一番近い薬局はどこですか。"],
  ["health","Vorrei fissare una visita.","I’d like to make an appointment.","Ich möchte einen Termin vereinbaren.","Quisiera pedir una cita.","Je voudrais prendre rendez-vous.","Я хотел бы записаться на приём.","我想预约看诊。","診察の予約をしたいです。"],
  ["health","È urgente.","It’s urgent.","Es ist dringend.","Es urgente.","C’est urgent.","Это срочно.","很紧急。","緊急です。"],
  ["health","Questa assicurazione è valida?","Is this insurance valid?","Ist diese Versicherung gültig?","¿Este seguro es válido?","Cette assurance est valable ?","Эта страховка действует?","这个保险有效吗？","この保険は使えますか。"],
  ["health","Ho una patologia cronica.","I have a chronic condition.","Ich habe eine chronische Erkrankung.","Tengo una enfermedad crónica.","J’ai une maladie chronique.","У меня хроническое заболевание.","我有慢性病。","持病があります。"],
  ["health","Mi gira la testa.","I feel dizzy.","Mir ist schwindelig.","Estoy mareado.","J’ai des vertiges.","У меня кружится голова.","我头晕。","めまいがします。"],
  ["health","Faccio fatica a respirare.","I’m having trouble breathing.","Ich bekomme schlecht Luft.","Me cuesta respirar.","J’ai du mal à respirer.","Мне трудно дышать.","我呼吸困难。","息苦しいです。"],
  ["health","Chiami un’ambulanza.","Call an ambulance.","Rufen Sie einen Krankenwagen.","Llame a una ambulancia.","Appelez une ambulance.","Вызовите скорую помощь.","请叫救护车。","救急車を呼んでください。"],

  ["services","Dov’è la stazione?","Where is the station?","Wo ist der Bahnhof?","¿Dónde está la estación?","Où se trouve la gare ?","Где вокзал?","车站在哪里？","駅はどこですか。"],
  ["services","Vorrei un biglietto.","I’d like a ticket.","Ich hätte gern eine Fahrkarte.","Quisiera un billete.","Je voudrais un billet.","Мне нужен билет.","我想买一张票。","切符を一枚お願いします。"],
  ["services","Solo andata, per favore.","One way, please.","Nur Hinfahrt, bitte.","Solo ida, por favor.","Un aller simple, s’il vous plaît.","В одну сторону, пожалуйста.","请给我单程票。","片道でお願いします。"],
  ["services","Quando passa il prossimo autobus?","When is the next bus?","Wann kommt der nächste Bus?","¿Cuándo pasa el próximo autobús?","Quand passe le prochain bus ?","Когда следующий автобус?","下一班公交车什么时候来？","次のバスは何時ですか。"],
  ["services","Questa è la fermata giusta?","Is this the right stop?","Ist das die richtige Haltestelle?","¿Esta es la parada correcta?","C’est le bon arrêt ?","Это нужная остановка?","这是正确的车站吗？","この停留所で合っていますか。"],
  ["services","Il treno è in ritardo?","Is the train delayed?","Hat der Zug Verspätung?","¿El tren lleva retraso?","Le train est en retard ?","Поезд опаздывает?","火车晚点了吗？","電車は遅れていますか。"],
  ["services","Posso pagare con la carta?","Can I pay by card?","Kann ich mit Karte zahlen?","¿Puedo pagar con tarjeta?","Je peux payer par carte ?","Можно оплатить картой?","可以刷卡吗？","カードで払えますか。"],
  ["services","Posso avere la ricevuta?","Can I have a receipt?","Kann ich eine Quittung bekommen?","¿Me da un recibo?","Je peux avoir un reçu ?","Можно получить чек?","可以给我收据吗？","領収書をもらえますか。"],
  ["services","Dov’è il bancomat più vicino?","Where is the nearest cash machine?","Wo ist der nächste Geldautomat?","¿Dónde está el cajero más cercano?","Où est le distributeur le plus proche ?","Где ближайший банкомат?","最近的自动取款机在哪里？","一番近いATMはどこですか。"],
  ["services","Vorrei aprire un conto.","I’d like to open an account.","Ich möchte ein Konto eröffnen.","Quisiera abrir una cuenta.","Je voudrais ouvrir un compte.","Я хотел бы открыть счёт.","我想开一个账户。","口座を開設したいです。"],
  ["services","Quali documenti servono?","Which documents do I need?","Welche Unterlagen brauche ich?","¿Qué documentos necesito?","Quels documents faut-il ?","Какие документы нужны?","需要哪些证件？","どの書類が必要ですか。"],
  ["services","Mi aiuta con questo modulo?","Could you help me with this form?","Können Sie mir mit diesem Formular helfen?","¿Me ayuda con este formulario?","Vous pouvez m’aider avec ce formulaire ?","Помогите мне с этой анкетой.","可以帮我填这张表吗？","この用紙の記入を手伝ってもらえますか。"],
  ["services","Ecco il mio documento.","Here is my ID.","Hier ist mein Ausweis.","Aquí tiene mi documento.","Voici ma pièce d’identité.","Вот мой документ.","这是我的证件。","こちらが身分証明書です。"],
  ["services","Quali sono gli orari di apertura?","What are the opening hours?","Wie sind die Öffnungszeiten?","¿Cuál es el horario de apertura?","Quels sont les horaires d’ouverture ?","Какие часы работы?","营业时间是什么时候？","営業時間は何時から何時までですか。"],
  ["services","Dov’è il bagno?","Where is the bathroom?","Wo ist die Toilette?","¿Dónde está el baño?","Où sont les toilettes ?","Где туалет?","洗手间在哪里？","トイレはどこですか。"],
  ["services","Ho perso questo oggetto.","I’ve lost this item.","Ich habe diesen Gegenstand verloren.","He perdido este objeto.","J’ai perdu cet objet.","Я потерял эту вещь.","我丢了这个东西。","これをなくしました。"],

  ["relationships","Ciao, mi chiamo Luca.","Hi, my name is Luca.","Hallo, ich heiße Luca.","Hola, me llamo Luca.","Bonjour, je m’appelle Luca.","Здравствуйте, меня зовут Лука.","你好，我叫Luca。","こんにちは、Lucaです。"],
  ["relationships","Piacere di conoscerti.","Nice to meet you.","Schön, dich kennenzulernen.","Encantado de conocerte.","Ravi de faire ta connaissance.","Приятно познакомиться.","很高兴认识你。","はじめまして。"],
  ["relationships","Di dove sei?","Where are you from?","Woher kommst du?","¿De dónde eres?","Tu viens d’où ?","Откуда ты?","你来自哪里？","どちらの出身ですか。"],
  ["relationships","Sono nuovo qui.","I’m new here.","Ich bin neu hier.","Soy nuevo aquí.","Je viens d’arriver ici.","Я здесь недавно.","我是新来的。","ここに来たばかりです。"],
  ["relationships","Ti va di prendere un caffè?","Would you like to get a coffee?","Möchtest du einen Kaffee trinken gehen?","¿Te apetece tomar un café?","Ça te dit de prendre un café ?","Хочешь выпить кофе?","要一起喝杯咖啡吗？","コーヒーでも飲みませんか。"],
  ["relationships","Sei libero questo fine settimana?","Are you free this weekend?","Hast du dieses Wochenende Zeit?","¿Estás libre este fin de semana?","Tu es libre ce week-end ?","Ты свободен в эти выходные?","你这个周末有空吗？","今週末は空いていますか。"],
  ["relationships","Grazie per l’invito.","Thanks for the invitation.","Danke für die Einladung.","Gracias por la invitación.","Merci pour l’invitation.","Спасибо за приглашение.","谢谢你的邀请。","誘ってくれてありがとうございます。"],
  ["relationships","Magari un’altra volta.","Maybe another time.","Vielleicht ein anderes Mal.","Quizá en otra ocasión.","Peut-être une autre fois.","Может быть, в другой раз.","下次吧。","また今度お願いします。"],
  ["relationships","Scusa per il ritardo.","Sorry I’m late.","Entschuldige die Verspätung.","Perdón por el retraso.","Désolé pour le retard.","Извини за опоздание.","对不起，我迟到了。","遅れてすみません。"],
  ["relationships","La penso diversamente.","I see it differently.","Ich sehe das anders.","Yo lo veo de otra manera.","Je vois les choses autrement.","Я думаю иначе.","我的看法不一样。","私は少し違う考えです。"],
  ["relationships","Ho bisogno di stare un po’ da solo.","I need some time alone.","Ich brauche etwas Zeit für mich.","Necesito estar un rato solo.","J’ai besoin d’un peu de temps seul.","Мне нужно немного побыть одному.","我需要独处一会儿。","少し一人になる時間が必要です。"],
  ["relationships","Per favore, non farlo.","Please don’t do that.","Bitte tu das nicht.","Por favor, no hagas eso.","S’il te plaît, ne fais pas ça.","Пожалуйста, не делай так.","请不要这样做。","それはやめてください。"],
  ["relationships","Credo ci sia stato un malinteso.","I think there was a misunderstanding.","Ich glaube, es gab ein Missverständnis.","Creo que ha habido un malentendido.","Je crois qu’il y a eu un malentendu.","Думаю, произошло недоразумение.","我想我们之间有误会。","誤解があったと思います。"],
  ["relationships","Nessun problema.","No problem.","Kein Problem.","No hay problema.","Pas de problème.","Без проблем.","没问题。","大丈夫です。"],
  ["relationships","Restiamo in contatto.","Let’s keep in touch.","Lass uns in Kontakt bleiben.","Sigamos en contacto.","Restons en contact.","Давай будем на связи.","我们保持联系。","また連絡しましょう。"],
  ["relationships","Scrivimi quando arrivi.","Message me when you get home.","Schreib mir, wenn du zu Hause bist.","Escríbeme cuando llegues a casa.","Écris-moi quand tu seras rentré.","Напиши мне, когда доберёшься домой.","到家后给我发消息。","家に着いたら連絡してください。"],
];

const phraseLanguageIndex = {it:1,en:2,de:3,es:4,fr:5,ru:6,zh:7,ja:8};

const phraseCategoryNames = {
  it:{help:"Chiedere e capire",home:"Casa",work:"Lavoro",health:"Salute",services:"Servizi",relationships:"Relazioni"},
  en:{help:"Ask and understand",home:"Home",work:"Work",health:"Health",services:"Services",relationships:"Relationships"},
  de:{help:"Nachfragen und verstehen",home:"Wohnen",work:"Arbeit",health:"Gesundheit",services:"Dienstleistungen",relationships:"Beziehungen"},
  es:{help:"Preguntar y entender",home:"Casa",work:"Trabajo",health:"Salud",services:"Servicios",relationships:"Relaciones"},
  fr:{help:"Demander et comprendre",home:"Logement",work:"Travail",health:"Santé",services:"Services",relationships:"Relations"},
  ru:{help:"Спрашивать и понимать",home:"Жильё",work:"Работа",health:"Здоровье",services:"Услуги",relationships:"Общение"},
  zh:{help:"询问与理解",home:"住房",work:"工作",health:"健康",services:"办事与出行",relationships:"人际交往"},
  ja:{help:"聞き返して理解する",home:"住まい",work:"仕事",health:"健康",services:"手続きと移動",relationships:"人間関係"},
};

const phraseCategoryDescriptions = {
  it:{help:"Ripetere, rallentare, confermare e guadagnare tempo.",home:"Affitto, bollette, guasti e vicini.",work:"Orari, compiti, dubbi e feedback.",health:"Sintomi, farmaci, visite ed emergenze.",services:"Trasporti, banca, documenti e pagamenti.",relationships:"Inviti, confini e piccoli malintesi."},
  en:{help:"Repeat, slow down, confirm, and buy time.",home:"Rent, bills, repairs, and neighbours.",work:"Schedules, tasks, questions, and feedback.",health:"Symptoms, medicine, appointments, and emergencies.",services:"Transport, banking, documents, and payments.",relationships:"Invitations, boundaries, and misunderstandings."},
  de:{help:"Wiederholen, verlangsamen, bestätigen und Zeit gewinnen.",home:"Miete, Rechnungen, Reparaturen und Nachbarn.",work:"Arbeitszeiten, Aufgaben, Fragen und Feedback.",health:"Symptome, Medikamente, Termine und Notfälle.",services:"Verkehr, Bank, Dokumente und Zahlungen.",relationships:"Einladungen, Grenzen und Missverständnisse."},
  es:{help:"Repetir, hablar más despacio, confirmar y ganar tiempo.",home:"Alquiler, facturas, averías y vecinos.",work:"Horarios, tareas, dudas y comentarios.",health:"Síntomas, medicamentos, citas y urgencias.",services:"Transporte, banco, documentos y pagos.",relationships:"Invitaciones, límites y malentendidos."},
  fr:{help:"Faire répéter, ralentir, confirmer et gagner du temps.",home:"Loyer, factures, réparations et voisins.",work:"Horaires, tâches, questions et retours.",health:"Symptômes, médicaments, rendez-vous et urgences.",services:"Transports, banque, documents et paiements.",relationships:"Invitations, limites et malentendus."},
  ru:{help:"Переспрашивать, просить говорить медленнее и уточнять.",home:"Аренда, счета, ремонт и соседи.",work:"График, задачи, вопросы и обратная связь.",health:"Симптомы, лекарства, приём и экстренные ситуации.",services:"Транспорт, банк, документы и оплата.",relationships:"Приглашения, личные границы и недоразумения."},
  zh:{help:"请对方重复、放慢速度、确认信息并争取思考时间。",home:"房租、账单、维修和邻里沟通。",work:"时间安排、任务、疑问和反馈。",health:"症状、药物、预约和紧急情况。",services:"交通、银行、证件和付款。",relationships:"邀请、界限和小误会。"},
  ja:{help:"聞き返す、ゆっくり話してもらう、確認する、考える時間を作る。",home:"家賃、光熱費、修理、近所付き合い。",work:"勤務時間、作業、質問、フィードバック。",health:"症状、薬、診察、緊急時。",services:"交通、銀行、書類、支払い。",relationships:"誘い方、断り方、境界線、誤解。"},
};

const survivalCopy = {
  it:{kicker:"KIT DI AUTONOMIA",title:"Le sei stanze della vita reale.",intro:"Impara prima le frasi che ti permettono di vivere, lavorare e risolvere problemi anche con una grammatica imperfetta.",priority:"PRIORITÀ",examples:"FRASI MODELLO"},
  en:{kicker:"INDEPENDENCE KIT",title:"Six rooms of real life.",intro:"Learn the phrases that let you live, work, and solve problems even before your grammar is perfect.",priority:"PRIORITY",examples:"MODEL PHRASES"},
  de:{kicker:"KIT FÜR DEN ALLTAG",title:"Sechs Bereiche des echten Lebens.",intro:"Lerne zuerst die Sätze, mit denen du leben, arbeiten und Probleme lösen kannst, auch wenn deine Grammatik noch nicht perfekt ist.",priority:"PRIORITÄT",examples:"BEISPIELSÄTZE"},
  es:{kicker:"KIT DE AUTONOMÍA",title:"Seis espacios de la vida real.",intro:"Aprende primero las frases que te permiten vivir, trabajar y resolver problemas aunque tu gramática todavía no sea perfecta.",priority:"PRIORIDAD",examples:"FRASES MODELO"},
  fr:{kicker:"KIT D’AUTONOMIE",title:"Six espaces de la vie réelle.",intro:"Apprends d’abord les phrases qui permettent de vivre, de travailler et de résoudre des problèmes, même avec une grammaire imparfaite.",priority:"PRIORITÉ",examples:"PHRASES MODÈLES"},
  ru:{kicker:"НАБОР ДЛЯ САМОСТОЯТЕЛЬНОСТИ",title:"Шесть сфер реальной жизни.",intro:"Сначала выучите фразы, которые помогут жить, работать и решать проблемы, даже если грамматика пока несовершенна.",priority:"ПРИОРИТЕТ",examples:"ПРИМЕРЫ ФРАЗ"},
  zh:{kicker:"独立生活工具包",title:"现实生活的六个场景。",intro:"先学会能帮助你生活、工作和解决问题的句子，即使语法还不完美也能开始行动。",priority:"优先",examples:"实用例句"},
  ja:{kicker:"自立のための基本セット",title:"実生活の六つの場面。",intro:"文法がまだ完璧でなくても、生活し、働き、問題を解決できる表現から先に覚えましょう。",priority:"優先",examples:"例文"},
};

const phraseUiCopy = {
  it:{visible:(n,t)=>`${n} di ${t} frasi`,more:"Mostra altre 20",search:"Cerca: lavoro, casa, aiuto…",empty:"Nessuna frase trovata",emptyText:"Prova una situazione più ampia, come “casa” o “lavoro”.",clear:"Azzera ricerca"},
  en:{visible:(n,t)=>`${n} of ${t} phrases`,more:"Show 20 more",search:"Search: work, home, help…",empty:"No phrases found",emptyText:"Try a broader situation, such as “home” or “work”.",clear:"Clear search"},
  de:{visible:(n,t)=>`${n} von ${t} Sätzen`,more:"Weitere 20 anzeigen",search:"Suchen: Arbeit, Wohnen, Hilfe…",empty:"Keine Sätze gefunden",emptyText:"Versuche einen größeren Bereich wie „Wohnen“ oder „Arbeit“.",clear:"Suche löschen"},
  es:{visible:(n,t)=>`${n} de ${t} frases`,more:"Mostrar 20 más",search:"Buscar: trabajo, casa, ayuda…",empty:"No se encontraron frases",emptyText:"Prueba una situación más amplia, como «casa» o «trabajo».",clear:"Borrar búsqueda"},
  fr:{visible:(n,t)=>`${n} phrases sur ${t}`,more:"Afficher 20 phrases de plus",search:"Rechercher : travail, logement, aide…",empty:"Aucune phrase trouvée",emptyText:"Essaie une situation plus large, comme « logement » ou « travail ».",clear:"Effacer la recherche"},
  ru:{visible:(n,t)=>`${n} из ${t} фраз`,more:"Показать ещё 20",search:"Поиск: работа, жильё, помощь…",empty:"Фразы не найдены",emptyText:"Попробуйте более широкую тему, например «жильё» или «работа».",clear:"Очистить поиск"},
  zh:{visible:(n,t)=>`显示 ${n}/${t} 个句子`,more:"再显示20句",search:"搜索：工作、住房、求助…",empty:"没有找到句子",emptyText:"请尝试“住房”或“工作”等更宽泛的场景。",clear:"清除搜索"},
  ja:{visible:(n,t)=>`${t}文中${n}文を表示`,more:"さらに20文を表示",search:"検索：仕事、住まい、助け…",empty:"文が見つかりません",emptyText:"「住まい」や「仕事」など、より広い場面で検索してください。",clear:"検索をクリア"},
};
